package markdown

import (
	"strings"

	"github.com/alecthomas/chroma"
)

var lexer747 = chroma.MustNewStyle("lexer747", chroma.StyleEntries{
	chroma.Background:             strings.Trim(" #1f1f1f", " "),
	chroma.Comment:                strings.Trim(" #6b995a", " "),
	chroma.CommentPreproc:         strings.Trim(" #6b995a", " "),
	chroma.CommentSpecial:         strings.Trim(" #6b995a", " "),
	chroma.Error:                  strings.Trim(" #f85149", " "),
	chroma.Generic:                strings.Trim(" #e6edf3", " "),
	chroma.GenericDeleted:         strings.Trim(" #490202", " "),
	chroma.GenericEmph:            strings.Trim(" ", " "),
	chroma.GenericError:           strings.Trim(" #ffa198", " "),
	chroma.GenericHeading:         strings.Trim(" #79c0ff", " "),
	chroma.GenericInserted:        strings.Trim(" #0f5323", " "),
	chroma.GenericOutput:          strings.Trim(" #8b949e", " "),
	chroma.GenericPrompt:          strings.Trim(" #8b949e", " "),
	chroma.GenericStrong:          strings.Trim(" ", " "),
	chroma.GenericSubheading:      strings.Trim(" #79c0ff", " "),
	chroma.GenericTraceback:       strings.Trim(" #ff7b72", " "),
	chroma.GenericUnderline:       strings.Trim(" underline", " "),
	chroma.Keyword:                strings.Trim(" #c486be", " "),
	chroma.KeywordConstant:        strings.Trim(" #79c0ff", " "),
	chroma.KeywordDeclaration:     strings.Trim(" #409ec8", " "),
	chroma.KeywordPseudo:          strings.Trim(" #79c0ff", " "),
	chroma.LineHighlight:          strings.Trim(" #6e7681", " "),
	chroma.LineNumbers:            strings.Trim(" #6e7681", " "),
	chroma.Literal:                strings.Trim(" #CD8F7A", " "),
	chroma.LiteralDate:            strings.Trim(" #CD8F7A", " "),
	chroma.LiteralStringAffix:     strings.Trim(" #CD8F7A", " "),
	chroma.LiteralStringDelimiter: strings.Trim(" #CD8F7A", " "),
	chroma.LiteralStringEscape:    strings.Trim(" #CD8F7A", " "),
	chroma.LiteralStringHeredoc:   strings.Trim(" #CD8F7A", " "),
	chroma.LiteralStringRegex:     strings.Trim(" #CD8F7A", " "),
	chroma.Name:                   strings.Trim(" #a8deff", " "),
	chroma.NameBuiltin:            strings.Trim(" #dcdbae", " "),
	chroma.NameClass:              strings.Trim(" #f0883e", " "),
	chroma.NameConstant:           strings.Trim(" #79c0ff", " "),
	chroma.NameDecorator:          strings.Trim(" #d2a8ff", " "),
	chroma.NameEntity:             strings.Trim(" #ffa657", " "),
	chroma.NameException:          strings.Trim(" #f0883e", " "),
	chroma.NameFunction:           strings.Trim(" #dcdbae", " "),
	chroma.NameLabel:              strings.Trim(" #79c0ff", " "),
	chroma.NameNamespace:          strings.Trim(" #ff7b72", " "),
	chroma.NameProperty:           strings.Trim(" #79c0ff", " "),
	chroma.NameTag:                strings.Trim(" #7ee787", " "),
	chroma.NameVariable:           strings.Trim(" #79c0ff", " "),
	chroma.NumberInteger:          strings.Trim(" #b6ceaa", " "),
	chroma.Operator:               strings.Trim(" #ff7b72", " "),
	chroma.Punctuation:            strings.Trim(" #ffd43b", " "),
	chroma.TextWhitespace:         strings.Trim(" #6e7681", " "),
})
