package markdown

import "github.com/alecthomas/chroma"

var lexer747 = chroma.MustNewStyle("lexer747", chroma.StyleEntries{
	chroma.Error:                  "#f85149",
	chroma.LineHighlight:          "bg:#6e7681",
	chroma.LineNumbers:            "#6e7681",
	chroma.Background:             "#e6edf3 bg:#0d1117",
	chroma.Keyword:                "#ff7b72",
	chroma.KeywordConstant:        "#79c0ff",
	chroma.KeywordPseudo:          "#79c0ff",
	chroma.Name:                   "#e6edf3",
	chroma.NameClass:              "bold #f0883e",
	chroma.NameConstant:           "bold #79c0ff",
	chroma.NameDecorator:          "bold #d2a8ff",
	chroma.NameEntity:             "#ffa657",
	chroma.NameException:          "bold #f0883e",
	chroma.NameFunction:           "bold #d2a8ff",
	chroma.NameLabel:              "bold #79c0ff",
	chroma.NameNamespace:          "#ff7b72",
	chroma.NameProperty:           "#79c0ff",
	chroma.NameTag:                "#7ee787",
	chroma.NameVariable:           "#79c0ff",
	chroma.Literal:                "#a5d6ff",
	chroma.LiteralDate:            "#79c0ff",
	chroma.LiteralStringAffix:     "#79c0ff",
	chroma.LiteralStringDelimiter: "#79c0ff",
	chroma.LiteralStringEscape:    "#79c0ff",
	chroma.LiteralStringHeredoc:   "#79c0ff",
	chroma.LiteralStringRegex:     "#79c0ff",
	chroma.Operator:               "bold #ff7b72",
	chroma.Comment:                "italic #8b949e",
	chroma.CommentSpecial:         "bold italic #8b949e",
	chroma.CommentPreproc:         "bold #8b949e",
	chroma.Generic:                "#e6edf3",
	chroma.GenericDeleted:         "#ffa198 bg:#490202",
	chroma.GenericEmph:            "italic",
	chroma.GenericError:           "#ffa198",
	chroma.GenericHeading:         "bold #79c0ff",
	chroma.GenericInserted:        "#56d364 bg:#0f5323",
	chroma.GenericOutput:          "#8b949e",
	chroma.GenericPrompt:          "#8b949e",
	chroma.GenericStrong:          "bold",
	chroma.GenericSubheading:      "#79c0ff",
	chroma.GenericTraceback:       "#ff7b72",
	chroma.GenericUnderline:       "underline",
	chroma.TextWhitespace:         "#6e7681",
})
